version: '3.8'

services:
  backend:
    build: ./backend
    container_name: synthetic_backend_fastapi
    ports:
      - "8000:8000"
    environment:
      - SEED=${SEED:-0000000000000000}
    networks:
      - synthetic_net

  frontend:
    build: ./frontend
    container_name: synthetic_frontend_ts
    ports:
      - "3000:3000"
    networks:
      - synthetic_net

networks:
  synthetic_net:
    driver: bridge